apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: shopflow/payment:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: JWT_SECRET
        - name: PORT
          value: "8004"