apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: shopflow/order:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: JWT_SECRET
        - name: PORT
          value: "8003"