apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: shopflow
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream auth_upstream { server auth:8001; }
        upstream product_upstream { server product:8002; }
        upstream order_upstream { server order:8003; }
        upstream payment_upstream { server payment:8004; }
        upstream notification_upstream { server notification:8005; }
        upstream userprofile_upstream { server user-profile:8006; }

        server {
            listen 80;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }

            location /auth/ {
                proxy_pass http://auth_upstream/;
                proxy_set_header Host $host;
            }
            location /products/ {
                proxy_pass http://product_upstream/;
            }
            location /orders/ {
                proxy_pass http://order_upstream/;
            }
            location /payments/ {
                proxy_pass http://payment_upstream/;
            }
            location /notifications/ {
                proxy_pass http://notification_upstream/;
            }
            location /profiles/ {
                proxy_pass http://userprofile_upstream/;
            }
        }
    }