apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: shopflow/notification:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8005
        env:
        - name: PORT
          value: "8005"