apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: shopflow/user-profile:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8006
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: shopflow-config
              key: JWT_SECRET
        - name: PORT
          value: "8006"